[package]
name = "ostree-cmd"
version = "0.1.0"
authors = ["William Manley <will@williammanley.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ostree-repo = { path = "../ostree-repo" }
structopt = "0.3"